#page title
page_title: StretchDesk # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: gb # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: https://j.gifs.com/Y6ZjpM.gif # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=com.codegoblin.stretchdesk # Enter Google Play Store URL.
presskit_download_link:
  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/logo.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: StretchDesk # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: A Stretching App For The Office!

enable_smart_app_banner: false # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: CodeGoblin Ltd
your_link: https://stretchdesk.co.uk
your_city:
email_address: stretchdesksupport@gmail.com
facebook_username: profile.php?id=61559024955894
instagram_username: stretchdeskapp
twitter_username:
github_username:
youtube_username:
mastodon_link:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Simple Stretches!
    description: Lot's of easy to do stretches for all levels of flexibility that can be easily performed at a desk.
    fontawesome_icon_name: heart

  - title: Customizable Routines!
    description: Fully customizable routines that are constantly randomized; keeping your mini workouts unique and interesting.
    fontawesome_icon_name: magic

  - title: Hourly Reminders!
    description: Reminders throughout the day to make sure you keep your body in check!
    fontawesome_icon_name: stopwatch

  - title: Plenty of Choice!
    description: Stretches for every muscle group to keep your body guessing and your brain engaged.
    fontawesome_icon_name: list

  - title: Premium Features!
    description: Ad free experience and even more stretches to perform, with more features coming soon.
    fontawesome_icon_name: coins

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/bgoffice.jpg # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
